# Generated by Django 3.2.5 on 2022-01-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_consult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='name',
        ),
        migrations.AddField(
            model_name='consult',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
    ]
