# Generated by Django 3.2.5 on 2022-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220130_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='user',
        ),
        migrations.AddField(
            model_name='consult',
            name='name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
