# Generated by Django 3.2.5 on 2022-01-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220130_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='name',
        ),
    ]
