# Generated by Django 3.2.5 on 2022-01-14 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_announcement_partnerinfo_volunteerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='subject',
            field=models.CharField(blank=True, default='Add Subject', max_length=60),
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ManyToManyField(related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
