# Generated by Django 3.2.5 on 2022-01-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220114_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
            preserve_default=False,
        ),
    ]
