# Generated by Django 3.2.5 on 2022-02-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220206_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Mailbox',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
