# Generated by Django 3.2.5 on 2022-05-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220206_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
